name: Run Preprocessing on Trigger

on:
  push:
    paths:
      - 'preprocessing/**'
  pull_request:
    paths:
      - 'preprocessing/**'
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install numpy pandas matplotlib scikit-learn seaborn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run preprocessing notebook
        run: python preprocessing/automate_MuhammadRizki.py

      - name: Commit and push processed dataset
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add preprocessing/*_output.ipynb preprocessing/*.csv
          git commit -m "Update processed dataset from GitHub Actions"
          git push
        env:
          # Required if you want to push from GitHub Actions
          # Generate a PAT with repo access and add it to repository secrets as GH_TOKEN
          # https://github.com/settings/tokens
          GIT_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
